### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by JimenaEB** [alexcastillla/digitalPostcard#1]
Sé que lo hiciste siguiendo el video, pero ahora sabes bien los que es un form y donde va el botón de submit, por fi actualizalo

**Comment by alexcastillla** [comment]
Corregido! Añadida etiquetas Form y etiquetas header, body y footer con el submit añadido en este último.

**Comment by JimenaEB** [comment]
Pero añadela dónde toca, no a todo el contenido

**Comment by alexcastillla** [comment]
Modificado! 🎈
